--CLIENTES
insert into Clientes (documento, nombre, vinculo) values (1, 'Faina Bennetts', 'Evento');
insert into Clientes (documento, nombre, vinculo) values (2, 'Eduino Serrier', 'Empleado');
insert into Clientes (documento, nombre, vinculo) values (3, 'Nari Furzey', 'Empleado');
insert into Clientes (documento, nombre, vinculo) values (4, 'Conrade Coombes', 'Evento');
insert into Clientes (documento, nombre, vinculo) values (5, 'Chickie Ivanyukov', 'Profesor');
insert into Clientes (documento, nombre, vinculo) values (6, 'Rebeka Rigg', 'Empleado');
insert into Clientes (documento, nombre, vinculo) values (7, 'Kizzie Joscelyn', 'Estudiante');
insert into Clientes (documento, nombre, vinculo) values (8, 'Ronda Knott', 'Egresado');
insert into Clientes (documento, nombre, vinculo) values (9, 'Reine Juhruke', 'Egresado');
insert into Clientes (documento, nombre, vinculo) values (10, 'Helene Coupland', 'Evento');
insert into Clientes (documento, nombre, vinculo) values (11, 'Grazia Bruster', 'Egresado');
insert into Clientes (documento, nombre, vinculo) values (12, 'Letisha Lascell', 'Profesor');
insert into Clientes (documento, nombre, vinculo) values (13, 'Rosemonde Prettyman', 'Profesor');
insert into Clientes (documento, nombre, vinculo) values (14, 'Juan Giorgietto', 'Empleado');
insert into Clientes (documento, nombre, vinculo) values (15, 'Marybeth Shea', 'Profesor');
insert into Clientes (documento, nombre, vinculo) values (16, 'Annabel Buckell', 'Profesor');
insert into Clientes (documento, nombre, vinculo) values (17, 'Morris Dipple', 'Estudiante');
insert into Clientes (documento, nombre, vinculo) values (18, 'Roberta Germain', 'Profesor invitado');
insert into Clientes (documento, nombre, vinculo) values (19, 'Derick Heersma', 'Evento');
insert into Clientes (documento, nombre, vinculo) values (20, 'Shawn Brou', 'Egresado');
insert into Clientes (documento, nombre, vinculo) values (21, 'Bambi Bovingdon', 'Profesor');
insert into Clientes (documento, nombre, vinculo) values (22, 'Gusella Shead', 'Egresado');
insert into Clientes (documento, nombre, vinculo) values (23, 'Joby Whittier', 'Evento');
insert into Clientes (documento, nombre, vinculo) values (24, 'Roxanne Rignall', 'Egresado');
insert into Clientes (documento, nombre, vinculo) values (25, 'Shannen Slyde', 'Estudiante');
insert into Clientes (documento, nombre, vinculo) values (26, 'Cad Greschke', 'Profesor');
insert into Clientes (documento, nombre, vinculo) values (27, 'Raf Draper', 'Profesor invitado');
insert into Clientes (documento, nombre, vinculo) values (28, 'Darla Beric', 'Padre');
insert into Clientes (documento, nombre, vinculo) values (29, 'Cyndy Pude', 'Empleado');
insert into Clientes (documento, nombre, vinculo) values (30, 'Shannah Johannesson', 'Egresado');

--OPERADORES
insert into Operadores (id, tipo, nombre) values (1, 'Hotel', 'Jade Plains Resort & Spa');
insert into Operadores (id, tipo, nombre) values (2, 'Persona', 'Estefania Cabal');
insert into Operadores (id, tipo, nombre) values (3, 'Vivienda Universitaria', 'Vision-oriented');
insert into Operadores (id, tipo, nombre) values (4, 'Hotel', 'Ivory Bear Hotel');
insert into Operadores (id, tipo, nombre) values (5, 'Vivienda Universitaria', 'object-oriented');
insert into Operadores (id, tipo, nombre) values (6, 'Persona', 'Joaquín Cambeiro');
insert into Operadores (id, tipo, nombre) values (7, 'Vivienda Universitaria', 'migration');
insert into Operadores (id, tipo, nombre) values (8, 'Vivienda Universitaria', 'multimedia');
insert into Operadores (id, tipo, nombre) values (9, 'Hostal', 'multi-state');
insert into Operadores (id, tipo, nombre) values (10, 'Persona', 'Jesús de la Cruz');
insert into Operadores (id, tipo, nombre) values (11, 'Hotel', 'Lunar Veil Resort');
insert into Operadores (id, tipo, nombre) values (12, 'Hotel', 'Gentle Ridge Hotel');
insert into Operadores (id, tipo, nombre) values (13, 'Hotel', 'Queens Dome Hotel');
insert into Operadores (id, tipo, nombre) values (14, 'Persona', 'Patricio Galán');
insert into Operadores (id, tipo, nombre) values (15, 'Hostal', 'Exclusive');
insert into Operadores (id, tipo, nombre) values (16, 'Persona', 'Roberto Cadaval');
insert into Operadores (id, tipo, nombre) values (17, 'Vivienda Universitaria', 'value-added');
insert into Operadores (id, tipo, nombre) values (18, 'Vivienda Universitaria', 'Function-based');
insert into Operadores (id, tipo, nombre) values (19, 'Persona', 'Felipe Cadaval');
insert into Operadores (id, tipo, nombre) values (20, 'Hotel', 'Starlight Resort');
insert into Operadores (id, tipo, nombre) values (21, 'Hostal', 'Future-proofed');
insert into Operadores (id, tipo, nombre) values (22, 'Vivienda Universitaria', 'fault-tolerant');
insert into Operadores (id, tipo, nombre) values (23, 'Vivienda Universitaria', 'system engine');
insert into Operadores (id, tipo, nombre) values (24, 'Hostal', 'eco-centric');
insert into Operadores (id, tipo, nombre) values (25, 'Vivienda Universitaria', 'contingency');
insert into Operadores (id, tipo, nombre) values (26, 'Persona', 'Thiago San Martín');
insert into Operadores (id, tipo, nombre) values (27, 'Hostal', 'Future-proofed');
insert into Operadores (id, tipo, nombre) values (28, 'Vivienda Universitaria', 'Managed');
insert into Operadores (id, tipo, nombre) values (29, 'Vivienda Universitaria', 'Right-sized');
insert into Operadores (id, tipo, nombre) values (30, 'Hostal', 'Team-oriented');

--SERVICIOS
insert into Servicios (id, nombre, descripcion, costo) values (1, 'Bañera', 'Cruickshank-Watsica', 54.64);
insert into Servicios (id, nombre, descripcion, costo) values (2, 'Servicio restaurante', 'Sipes, Donnelly and Gottlieb', 90.41);
insert into Servicios (id, nombre, descripcion, costo) values (3, 'Parqueadero', 'Yundt-Maggio', 21.43);
insert into Servicios (id, nombre, descripcion, costo) values (4, 'Cocineta', 'Wehner, Lynch and Paucek', 99.34);
insert into Servicios (id, nombre, descripcion, costo) values (5, 'Minibar', 'Graham, Frami and Anderson', 56.76);
insert into Servicios (id, nombre, descripcion, costo) values (6, 'WiFi', 'Halvorson LLC', 19.87);
insert into Servicios (id, nombre, descripcion, costo) values (7, 'TV cable', 'Mayert, Stark and Lang', 64.9);
insert into Servicios (id, nombre, descripcion, costo) values (8, 'TV satelital', 'Durgan LLC', 17.57);
insert into Servicios (id, nombre, descripcion, costo) values (9, 'Gimnasio', 'Smitham-Kautzer', 42.85);
insert into Servicios (id, nombre, descripcion, costo) values (10, 'Yacuzzi', 'Dicki, Johnson and Howell', 43.08);
insert into Servicios (id, nombre, descripcion, costo) values (11, 'Recepcion 24h', 'Terry Inc', 96.16);
insert into Servicios (id, nombre, descripcion, costo) values (12, 'Internet Incluido', 'Gibson and Sons', 0);
insert into Servicios (id, nombre, descripcion, costo) values (13, 'Desayuno incluido', 'Beahan, Friesen and Bauch', 0);
insert into Servicios (id, nombre, descripcion, costo) values (14, 'challenge', 'Cormier, Bins and Bartell', 82.48);
insert into Servicios (id, nombre, descripcion, costo) values (15, 'installation', 'Berge-Pagac', 86.07);
insert into Servicios (id, nombre, descripcion, costo) values (16, 'national', 'Shields Group', 78.61);
insert into Servicios (id, nombre, descripcion, costo) values (17, 'Team-oriented', 'Jenkins-Stroman', 89.47);
insert into Servicios (id, nombre, descripcion, costo) values (18, 'leverage', 'Larson-Lebsack', 65.8);
insert into Servicios (id, nombre, descripcion, costo) values (19, 'Adaptive', 'Walker-Fay', 6.08);
insert into Servicios (id, nombre, descripcion, costo) values (20, 'Phased', 'Watsica, Schumm and Ryan', 18.28);
insert into Servicios (id, nombre, descripcion, costo) values (21, 'Balanced', 'Willms-Wiegand', 82.53);
insert into Servicios (id, nombre, descripcion, costo) values (22, 'Quality-focused', 'Bins-Torphy', 67.59);
insert into Servicios (id, nombre, descripcion, costo) values (23, 'system engine', 'Reichel and Sons', 99.86);
insert into Servicios (id, nombre, descripcion, costo) values (24, 'core', 'Smith-Braun', 67.29);
insert into Servicios (id, nombre, descripcion, costo) values (25, 'Networked', 'Tremblay-Glover', 22.77);
insert into Servicios (id, nombre, descripcion, costo) values (26, 'Focused', 'Wisoky, Trantow and Littel', 41.03);
insert into Servicios (id, nombre, descripcion, costo) values (27, 'well-modulated', 'Spinka, Rosenbaum and Aufderhar', 78.03);
insert into Servicios (id, nombre, descripcion, costo) values (28, 'customer loyalty', 'Lakin and Sons', 9.31);
insert into Servicios (id, nombre, descripcion, costo) values (29, 'Mandatory', 'Botsford-Hessel', 27.54);
insert into Servicios (id, nombre, descripcion, costo) values (30, 'real-time', 'Schoen and Sons', 41.95);

--Alojamientos
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (1, 'Vivienda', 'dreis0', 'Plaza', 'conglomeration', 59.13, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (2, 'HabitacionVivienda', 'jkilalea1', 'Alley', 'clear-thinking', 45.12, 1);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (3, 'Apartamento', 'kbakeup2', 'Avenue', 'Front-line', 10.99, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (4, 'HabitacionVivienda', 'smcgettigan3', 'Trail', 'functionalities', 89.66, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (5, 'HabitacionUniversitaria', 'jhowlings4', 'Alley', 'Grass-roots', 66.73, 180);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (6, 'HabitacionVivienda', 'egreenrod5', 'Lane', 'Multi-tiered', 59.09, 180);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (7, 'HabitacionH', 'bsurphliss6', 'Court', 'hub', 60.31, 180);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (8, 'Apartamento', 'gburchfield7', 'Junction', 'definition', 21.64, 180);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (9, 'HabitacionVivienda', 'nhardage8', 'Hill', 'user-facing', 63.62, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (10, 'HabitacionH', 'joddy9', 'Place', 'product', 36.09, 180);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (11, 'HabitacionUniversitaria', 'mbrooksbiea', 'Drive', 'Proactive', 91.13, 180);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (12, 'HabitacionUniversitaria', 'tatyeab', 'Circle', 'hub', 24.67, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (13, 'HabitacionH', 'lkrzyzowskic', 'Alley', 'needs-based', 81.9, 1);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (14, 'HabitacionUniversitaria', 'amettricked', 'Parkway', 'Monitored', 31.79, 1);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (15, 'HabitacionH', 'hbreee', 'Hill', 'Compatible', 87.66, 1);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (16, 'HabitacionUniversitaria', 'kmasseof', 'Pass', 'reciprocal', 2.15, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (17, 'HabitacionH', 'jferng', 'Plaza', 'dedicated', 53.85, 1);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (18, 'HabitacionUniversitaria', 'manthoneyh', 'Pass', 'dedicated', 4.27, 180);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (19, 'Vivienda', 'qdebankei', 'Pass', 'zero defect', 15.81, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (20, 'Vivienda', 'lvowlesj', 'Parkway', 'neutral', 23.95, 1);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (21, 'Vivienda', 'sbyartk', 'Pass', 'intranet', 85.85, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (22, 'HabitacionVivienda', 'eharkinsl', 'Crossing', 'paradigm', 74.01, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (23, 'HabitacionVivienda', 'cmcgarvam', 'Center', 'Enhanced', 54.77, 1);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (24, 'HabitacionUniversitaria', 'dvasilmanovn', 'Terrace', 'Fundamental', 93.51, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (25, 'HabitacionVivienda', 'rcowdeno', 'Crossing', 'installation', 96.68, 1);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (26, 'Apartamento', 'amalecp', 'Plaza', 'background', 18.39, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (27, 'HabitacionUniversitaria', 'vpawnsfordq', 'Hill', 'system engine', 92.02, 180);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (28, 'HabitacionH', 'zmossonr', 'Terrace', 'firmware', 16.32, 180);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (29, 'HabitacionVivienda', 'dkulls', 'Terrace', 'Progressive', 14.06, 1);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, minimoPeriodo) values (30, 'Vivienda', 'tpendryt', 'Court', 'Open-architected', 14.78, 180);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (31, 'HabitacionH', 'exuding', 'Lane', 'Aimbu', 84.13, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (32, 'HabitacionVivienda', 'Operative', 'Street', 'Jaxnation', 11.8, 280);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (33, 'HabitacionUniversitaria', 'Automated', 'Point', 'Zooveo', 48.87, 1);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (34, 'vivienda', 'extranet', 'Plaza', 'Jabbersphere', 73.72, 60);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (35, 'HabitacionVivienda', 'Graphical User Interface', 'Court', 'Kimia', 38.61, 280);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (36, 'Apartamento', 'hierarchy', 'Avenue', 'Wikibox', 24.66, 60);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (37, 'HabitacionH', 'Automated', 'Crossing', 'Roombo', 50.8, 60);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (38, 'vivienda', 'Optional', 'Drive', 'Gabtune', 54.61, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (39, 'HabitacionVivienda', 'architecture', 'Crossing', 'Topicstorm', 33.83, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (40, 'vivienda', 'flexibility', 'Terrace', 'Youfeed', 59.12, 280);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (41, 'HabitacionUniversitaria', 'contextually-based', 'Crossing', 'Gigabox', 44.47, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (42, 'HabitacionVivienda', 'upward-trending', 'Terrace', 'Jaxworks', 34.3, 60);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (43, 'vivienda', 'encoding', 'Hill', 'Skyble', 44.87, 280);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (44, 'Apartamento', 'moratorium', 'Pass', 'Gabtype', 48.22, 60);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (45, 'HabitacionH', 'composite', 'Lane', 'Photobug', 53.75, 280);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (46, 'HabitacionVivienda', 'logistical', 'Court', 'Tagtune', 6.53, 60);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (47, 'HabitacionVivienda', 'productivity', 'Crossing', 'Tazzy', 15.36, 1);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (48, 'HabitacionUniversitaria', 'Optimized', 'Drive', 'Tagcat', 94.85, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (49, 'HabitacionVivienda', 'Object-based', 'Parkway', 'Lazzy', 1.71, 60);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (50, 'vivienda', '24/7', 'Avenue', 'Oyoloo', 26.74, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (51, 'HabitacionVivienda', '4th generation', 'Parkway', 'Yamia', 37.62, 60);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (52, 'HabitacionUniversitaria', 'Open-source', 'Terrace', 'Oozz', 16.72, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (53, 'HabitacionUniversitaria', 'human-resource', 'Trail', 'Aibox', 27.41, 280);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (54, 'vivienda', 'needs-based', 'Place', 'Feedfish', 58.16, 280);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (55, 'HabitacionUniversitaria', 'well-modulated', 'Trail', 'Dablist', 75.34, 60);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (56, 'vivienda', 'real-time', 'Terrace', 'Wikizz', 44.69, 60);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (57, 'HabitacionH', 'bifurcated', 'Road', 'Photobean', 90.71, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (58, 'HabitacionUniversitaria', 'hub', 'Point', 'Meeveo', 39.24, 60);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (59, 'HabitacionVivienda', 'Self-enabling', 'Trail', 'Yombu', 75.58, 280);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (60, 'Apartamento', 'Innovative', 'Lane', 'Oozz', 68.54, 60);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (61, 'HabitacionVivienda', 'Sharable', 'Place', 'Aimbu', 13.4, 280);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (62, 'HabitacionH', 'Visionary', 'Alley', 'Latz', 14.83, 280);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (63, 'HabitacionH', 'intermediate', 'Park', 'Linklinks', 16.14, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (64, 'HabitacionH', 'national', 'Lane', 'Jabbercube', 83.45, 1);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (65, 'HabitacionVivienda', 'complexity', 'Center', 'Dynabox', 59.24, 280);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (66, 'Apartamento', 'local', 'Center', 'Wikizz', 94.96, 60);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (67, 'HabitacionVivienda', 'foreground', 'Point', 'Pixonyx', 41.15, 1);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (68, 'HabitacionH', 'high-level', 'Avenue', 'Flipstorm', 80.0, 280);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (69, 'vivienda', 'Robust', 'Circle', 'Quimm', 44.24, 60);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (70, 'vivienda', 'Reduced', 'Junction', 'Realfire', 39.28, 1);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (71, 'Apartamento', 'discrete', 'Drive', 'Brainlounge', 7.61, 280);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (72, 'HabitacionH', 'Fundamental', 'Circle', 'Fiveclub', 93.13, 1);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (73, 'HabitacionH', 'contextually-based', 'Road', 'Gigashots', 85.24, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (74, 'HabitacionVivienda', 'Assimilated', 'Trail', 'Muxo', 40.81, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (75, 'vivienda', 'Intuitive', 'Alley', 'Zoomdog', 59.28, 60);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (76, 'HabitacionUniversitaria', 'product', 'Street', 'Feedspan', 26.26, 60);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (77, 'Apartamento', 'User-centric', 'Way', 'Realpoint', 50.81, 280);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (78, 'HabitacionH', 'Balanced', 'Trail', 'Devify', 14.44, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (79, 'HabitacionH', 'access', 'Court', 'Gabtune', 23.05, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (80, 'Apartamento', 'Focused', 'Circle', 'Leenti', 5.08, 60);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (81, 'HabitacionVivienda', 'Networked', 'Lane', 'Oodoo', 55.96, 280);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (82, 'HabitacionVivienda', 'Upgradable', 'Hill', 'Brainsphere', 32.45, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (83, 'HabitacionH', 'Face to face', 'Plaza', 'Skimia', 40.09, 280);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (84, 'HabitacionVivienda', 'motivating', 'Center', 'Brainlounge', 5.54, 60);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (85, 'HabitacionVivienda', 'actuating', 'Pass', 'Meevee', 91.5, 60);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (86, 'Apartamento', 'Synchronised', 'Pass', 'InnoZ', 78.84, 280);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (87, 'HabitacionH', 'Synchronised', 'Way', 'Realfire', 53.89, 1);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (88, 'HabitacionUniversitaria', 'transitional', 'Court', 'Brainsphere', 1.74, 280);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (89, 'HabitacionVivienda', 'Profit-focused', 'Court', 'Teklist', 58.42, 60);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (90, 'HabitacionUniversitaria', 'intranet', 'Point', 'Brainlounge', 81.57, 1);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (91, 'vivienda', 'well-modulated', 'Street', 'Browsetype', 83.35, 60);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (92, 'HabitacionH', 'Polarised', 'Drive', 'Zoomlounge', 88.44, 280);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (93, 'Apartamento', 'Networked', 'Street', 'Feednation', 16.75, 280);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (94, 'Apartamento', 'leverage', 'Center', 'Realbuzz', 34.24, 1);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (95, 'HabitacionUniversitaria', 'infrastructure', 'Road', 'Skinder', 23.06, 30);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (96, 'vivienda', 'analyzer', 'Lane', 'Dazzlesphere', 74.03, 60);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (97, 'HabitacionH', 'multimedia', 'Point', 'Photobug', 92.2, 1);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (98, 'Apartamento', 'knowledge base', 'Drive', 'Viva', 93.91, 280);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (99, 'vivienda', 'Implemented', 'Road', 'Eadel', 63.97, 1);
insert into Alojamientos (id, tipo, nombre, ubicacion, descripcion, costo, MinimoPeriodo) values (100, 'HabitacionUniversitaria', '24/7', 'Crossing', 'Voonix', 16.34, 1);