
SELECT CLIENTES.DOCUMENTO, clientes.vinculo, CLIENTES.NOMBRE, ALOJAMIENTOS.TIPO, RESERVAS.FECHALLEGADA, RESERVAS.CANTIDADDIAS
FROM CLIENTES, OFERTAS, RESERVAS, RESERVASCLIENTE, alojamientos
WHERE CLIENTES.DOCUMENTO = RESERVASCLIENTE.CLIENTEID
AND RESERVASCLIENTE.RESERVAID= RESERVAS.ID
AND OFERTAS.ID = RESERVAS.OFERTA
AND OFERTAS.ALOJAMIENTOID = ALOJAMIENTOS.ID
AND RESERVAS.FECHALLEGADA BETWEEN TO_DATE('1/1/2017','DD/MM/YYYY')
AND TO_DATE('1/1/2018','DD/MM/YYYY')
order by CLIENTES.NOMBRE;