
SELECT CLIENTES.DOCUMENTO
FROM CLIENTES, OFERTAS, RESERVAS, RESERVASCLIENTE
WHERE CLIENTES.DOCUMENTO = RESERVASCLIENTE.CLIENTEID
AND RESERVASCLIENTE.RESERVAID= RESERVAS.ID
AND OFERTAS.ID = RESERVAS.OFERTA
AND OFERTAS.ID = 1
AND RESERVAS.FECHALLEGADA BETWEEN TO_DATE('1/1/2017','DD/MM/YYYY')
AND TO_DATE('1/1/2018','DD/MM/YYYY') ;