SELECT CASt(TO_CHAR(RESERVAS.FECHALLEGADA,'IW') as int) as semana,ofertas.id, sum(OFERTAS.PRECIOESTADIA*RESERVAS.CANTIDADDIAS)AS ingresos, count(*) as numreservas
FROM RESERVAS, OFERTAS
WHERE RESERVAS.OFERTA=OFERTAS.ID 
group by TO_CHAR(RESERVAS.FECHALLEGADA,'IW'), CASt(TO_CHAR(RESERVAS.FECHALLEGADA,'IW') as int), RESERVAS.FECHALLEGADA, 'IW', ofertas.id
order by  TO_CHAR(RESERVAS.FECHALLEGADA,'IW');


SELECT  CASt(TO_CHAR(RESERVAS.FECHALLEGADA,'IW') as int) as semana,OPERADORES.id, sum(OFERTAS.PRECIOESTADIA*RESERVAS.CANTIDADDIAS)AS ingresos, count(*) as numreservas
FROM RESERVAS, OFERTAS, OPERADORES
WHERE RESERVAS.OFERTA=OFERTAS.ID 
and OFERTAS.OPERADOR = OPERADORES.ID
group by TO_CHAR(RESERVAS.FECHALLEGADA,'IW'), RESERVAS.FECHALLEGADA, 'IW', OPERADORES.id, CASt(TO_CHAR(RESERVAS.FECHALLEGADA,'IW') as int)
order by  TO_CHAR(RESERVAS.FECHALLEGADA,'IW');