-- RESERVAS MENSUALES
SELECT t.* FROM(
 SELECT CLIENTES.DOCUMENTO,  TO_CHAR(RESERVAS.FECHALLEGADA,'YYYY') AS AÑO, COUNT(*) AS NUMRESERVAS
 FROM CLIENTES, RESERVAS, RESERVASCLIENTE
 WHERE RESERVAS.ID=RESERVASCLIENTE.RESERVAID
 AND RESERVASCLIENTE.CLIENTEID = CLIENTES.DOCUMENTO 
 group by CLIENTES.DOCUMENTO, TO_CHAR(RESERVAS.FECHALLEGADA,'YYYY')
 ORDER BY CLIENTES.DOCUMENTO) t
 WHERE T.NUMRESERVAS >= 12;
 
 --ALOJAMIENTOS CAROS
 
 SELECT T.* FROM(
 SELECT CLIENTES.DOCUMENTO,  COUNT(*) AS NUMRESERVAS, SUM(case when OFERTAS.PRECIOESTADIA > 150 THEN 1 ELSE 0 END) AS ALOJAMIENTOSCAROS
 FROM CLIENTES, RESERVAS, RESERVASCLIENTE, OFERTAS
 WHERE RESERVAS.ID=RESERVASCLIENTE.RESERVAID
 AND RESERVASCLIENTE.CLIENTEID = CLIENTES.DOCUMENTO 
 AND RESERVAS.OFERTA = OFERTAS.ID
 group by CLIENTES.DOCUMENTO) T
 WHERE T.NUMRESERVAS = T.ALOJAMIENTOSCAROS;
 
 -- solo suites
 SELECT CLIENTES.DOCUMENTO,  COUNT(*) AS NUMRESERVAS, SUM(case when HABITACIONESHOTEL.TIPO ='Suite' THEN 1 ELSE 0 END) AS Suites
 FROM CLIENTES, RESERVAS, RESERVASCLIENTE, OFERTAS, habitacioneshotel
 WHERE RESERVAS.ID=RESERVASCLIENTE.RESERVAID
 AND RESERVASCLIENTE.CLIENTEID = CLIENTES.DOCUMENTO 
 AND RESERVAS.OFERTA = OFERTAS.ID
 AND OFERTAS.ALOJAMIENTOID = HABITACIONESHOTEL.id
 group by CLIENTES.DOCUMENTO;