-- RESERVAS MENSUALES
 SELECT T1.* FROM(
 SELECT CLIENTES.DOCUMENTO, 
 TO_CHAR(RESERVAS.FECHALLEGADA,'YYYY') AS AÑO,
 COUNT(*) AS NUMRESERVAS
 FROM CLIENTES, RESERVAS, RESERVASCLIENTE
 WHERE RESERVAS.ID=RESERVASCLIENTE.RESERVAID
 AND RESERVASCLIENTE.CLIENTEID = CLIENTES.DOCUMENTO 
 GROUP BY CLIENTES.DOCUMENTO,
 TO_CHAR(RESERVAS.FECHALLEGADA,'YYYY')
 ORDER BY CLIENTES.DOCUMENTO) T1
 WHERE T1.NUMRESERVAS >= 12;
 
 
 --ALOJAMIENTOS CAROS
 
 SELECT T2.* FROM(
 SELECT CLIENTES.DOCUMENTO,  
 COUNT(*) AS NUMRESERVAS, 
 SUM(case when OFERTAS.PRECIOESTADIA > 150 THEN 1 ELSE 0 END) AS ALOJAMIENTOSCAROS
 FROM CLIENTES, RESERVAS, RESERVASCLIENTE, OFERTAS
 WHERE RESERVAS.ID=RESERVASCLIENTE.RESERVAID
 AND RESERVASCLIENTE.CLIENTEID = CLIENTES.DOCUMENTO 
 AND RESERVAS.OFERTA = OFERTAS.ID
 group by CLIENTES.DOCUMENTO) T2
 WHERE T2.NUMRESERVAS = T2.ALOJAMIENTOSCAROS;
 
 -- solo suites
  SELECT T3.* FROM(
 SELECT CLIENTES.DOCUMENTO,
 COUNT(*) AS NUMRESERVAS, 
 SUM(case when HABITACIONESHOTEL.TIPO ='Suite' THEN 1 ELSE 0 END) AS Suites
 FROM CLIENTES, RESERVAS, RESERVASCLIENTE, OFERTAS, habitacioneshotel
 WHERE RESERVAS.ID=RESERVASCLIENTE.RESERVAID
 AND RESERVASCLIENTE.CLIENTEID = CLIENTES.DOCUMENTO 
 AND RESERVAS.OFERTA = OFERTAS.ID
 AND OFERTAS.ALOJAMIENTOID = HABITACIONESHOTEL.id
 group by CLIENTES.DOCUMENTO) T3
 WHERE t3.suites = T3.NUMRESERVAS;
 
 