-- RESERVAS MENSUALES
SELECT "A1"."DOCUMENTO" "DOCUMENTO","A1"."AÑO" "AÑO","A1"."NUMRESERVAS" "NUMRESERVAS" FROM  (SELECT "A4"."DOCUMENTO" "DOCUMENTO",TO_CHAR("A3"."FECHALLEGADA",'YYYY') "AÑO",COUNT(*) "NUMRESERVAS" FROM "ISIS2304A021810"."CLIENTES" "A4","ISIS2304A021810"."RESERVAS" "A3","ISIS2304A021810"."RESERVASCLIENTE" "A2" WHERE "A3"."ID"="A2"."RESERVAID" AND "A2"."CLIENTEID"="A4"."DOCUMENTO" GROUP BY "A4"."DOCUMENTO",TO_CHAR("A3"."FECHALLEGADA",'YYYY') ORDER BY "A4"."DOCUMENTO") "A1" WHERE "A1"."NUMRESERVAS">=12;
 
 SELECT t1.* FROM(
 SELECT CLIENTES.DOCUMENTO,  TO_CHAR(RESERVAS.FECHALLEGADA,'YYYY') AS AÑO, COUNT(*) AS NUMRESERVAS
 FROM CLIENTES, RESERVAS, RESERVASCLIENTE
 WHERE RESERVAS.ID=RESERVASCLIENTE.RESERVAID
 AND RESERVASCLIENTE.CLIENTEID = CLIENTES.DOCUMENTO 
 group by CLIENTES.DOCUMENTO, TO_CHAR(RESERVAS.FECHALLEGADA,'YYYY')
 ORDER BY CLIENTES.DOCUMENTO) t1
 WHERE T1.NUMRESERVAS >= 12;
 
 
 --ALOJAMIENTOS CAROS
 
 SELECT T2.* FROM(
 SELECT CLIENTES.DOCUMENTO,  COUNT(*) AS NUMRESERVAS, SUM(case when OFERTAS.PRECIOESTADIA > 150 THEN 1 ELSE 0 END) AS ALOJAMIENTOSCAROS
 FROM CLIENTES, RESERVAS, RESERVASCLIENTE, OFERTAS
 WHERE RESERVAS.ID=RESERVASCLIENTE.RESERVAID
 AND RESERVASCLIENTE.CLIENTEID = CLIENTES.DOCUMENTO 
 AND RESERVAS.OFERTA = OFERTAS.ID
 group by CLIENTES.DOCUMENTO) T2
 WHERE T2.NUMRESERVAS = T2.ALOJAMIENTOSCAROS;
 
 -- solo suites
  SELECT T3.* FROM(
 SELECT CLIENTES.DOCUMENTO,  COUNT(*) AS NUMRESERVAS, SUM(case when HABITACIONESHOTEL.TIPO ='Suite' THEN 1 ELSE 0 END) AS Suites
 FROM CLIENTES, RESERVAS, RESERVASCLIENTE, OFERTAS, habitacioneshotel
 WHERE RESERVAS.ID=RESERVASCLIENTE.RESERVAID
 AND RESERVASCLIENTE.CLIENTEID = CLIENTES.DOCUMENTO 
 AND RESERVAS.OFERTA = OFERTAS.ID
 AND OFERTAS.ALOJAMIENTOID = HABITACIONESHOTEL.id
 group by CLIENTES.DOCUMENTO) T3
 WHERE t3.suites = T3.NUMRESERVAS;
 
 