--Ofertas
SELECT CAST(TO_CHAR(RESERVAS.FECHALLEGADA,'IW') AS INT) AS SEMANA,
OFERTAS.ID, 
SUM(OFERTAS.PRECIOESTADIA*RESERVAS.CANTIDADDIAS)AS INGRESOS, 
COUNT(*) AS NUMRESERVAS
FROM RESERVAS, OFERTAS
WHERE RESERVAS.OFERTA=OFERTAS.ID 
GROUP BY TO_CHAR(RESERVAS.FECHALLEGADA,'IW'),
CAST(TO_CHAR(RESERVAS.FECHALLEGADA,'IW') AS INT), 
RESERVAS.FECHALLEGADA, 'IW', 
OFERTAS.ID
ORDER BY  TO_CHAR(RESERVAS.FECHALLEGADA,'IW');

SELECT CAST(TO_CHAR("A2"."FECHALLEGADA",'IW') AS int) "SEMANA","A1"."ID" "ID",SUM("A1"."PRECIOESTADIA"*"A2"."CANTIDADDIAS") "INGRESOS",COUNT(*) "NUMRESERVAS" FROM "ISIS2304A021810"."RESERVAS" "A2","ISIS2304A021810"."OFERTAS" "A1" WHERE "A2"."OFERTA"="A1"."ID" GROUP BY TO_CHAR("A2"."FECHALLEGADA",'IW'),CAST(TO_CHAR("A2"."FECHALLEGADA",'IW') AS int),"A2"."FECHALLEGADA","A1"."ID" ORDER BY TO_CHAR("A2"."FECHALLEGADA",'IW');

--Operadores

SELECT  CAST(TO_CHAR(RESERVAS.FECHALLEGADA,'IW') AS INT) AS SEMANA,
OPERADORES.ID, SUM(OFERTAS.PRECIOESTADIA*RESERVAS.CANTIDADDIAS)AS INGRESOS, 
COUNT(*) AS NUMRESERVAS
FROM RESERVAS, OFERTAS, OPERADORES
WHERE RESERVAS.OFERTA=OFERTAS.ID 
AND OFERTAS.OPERADOR = OPERADORES.ID
GROUP BY TO_CHAR(RESERVAS.FECHALLEGADA,'IW'), 
RESERVAS.FECHALLEGADA, 'IW', OPERADORES.ID, 
CAST(TO_CHAR(RESERVAS.FECHALLEGADA,'IW') AS INT)
ORDER BY  TO_CHAR(RESERVAS.FECHALLEGADA,'IW'),COUNT(*);

SELECT CAST(TO_CHAR("A3"."FECHALLEGADA",'IW') AS int) "SEMANA","A1"."ID" "ID",SUM("A2"."PRECIOESTADIA"*"A3"."CANTIDADDIAS") "INGRESOS",COUNT(*) "NUMRESERVAS" FROM "ISIS2304A021810"."RESERVAS" "A3","ISIS2304A021810"."OFERTAS" "A2","ISIS2304A021810"."OPERADORES" "A1" WHERE "A3"."OFERTA"="A2"."ID" AND "A2"."OPERADOR"="A1"."ID" GROUP BY TO_CHAR("A3"."FECHALLEGADA",'IW'),"A3"."FECHALLEGADA","A1"."ID",CAST(TO_CHAR("A3"."FECHALLEGADA",'IW') AS int) ORDER BY TO_CHAR("A3"."FECHALLEGADA",'IW');