--Ofertas
SELECT CASt(TO_CHAR(RESERVAS.FECHALLEGADA,'IW') as int) as semana,ofertas.id, sum(OFERTAS.PRECIOESTADIA*RESERVAS.CANTIDADDIAS)AS ingresos, count(*) as numreservas
FROM RESERVAS, OFERTAS
WHERE RESERVAS.OFERTA=OFERTAS.ID 
group by TO_CHAR(RESERVAS.FECHALLEGADA,'IW'), CASt(TO_CHAR(RESERVAS.FECHALLEGADA,'IW') as int), RESERVAS.FECHALLEGADA, 'IW', ofertas.id
order by  TO_CHAR(RESERVAS.FECHALLEGADA,'IW');

SELECT CAST(TO_CHAR("A2"."FECHALLEGADA",'IW') AS int) "SEMANA","A1"."ID" "ID",SUM("A1"."PRECIOESTADIA"*"A2"."CANTIDADDIAS") "INGRESOS",COUNT(*) "NUMRESERVAS" FROM "ISIS2304A021810"."RESERVAS" "A2","ISIS2304A021810"."OFERTAS" "A1" WHERE "A2"."OFERTA"="A1"."ID" GROUP BY TO_CHAR("A2"."FECHALLEGADA",'IW'),CAST(TO_CHAR("A2"."FECHALLEGADA",'IW') AS int),"A2"."FECHALLEGADA","A1"."ID" ORDER BY TO_CHAR("A2"."FECHALLEGADA",'IW');

--Operadores

SELECT  CASt(TO_CHAR(RESERVAS.FECHALLEGADA,'IW') as int) as semana,OPERADORES.id, sum(OFERTAS.PRECIOESTADIA*RESERVAS.CANTIDADDIAS)AS ingresos, count(*) as numreservas
FROM RESERVAS, OFERTAS, OPERADORES
WHERE RESERVAS.OFERTA=OFERTAS.ID 
and OFERTAS.OPERADOR = OPERADORES.ID
group by TO_CHAR(RESERVAS.FECHALLEGADA,'IW'), RESERVAS.FECHALLEGADA, 'IW', OPERADORES.id, CASt(TO_CHAR(RESERVAS.FECHALLEGADA,'IW') as int)
order by  TO_CHAR(RESERVAS.FECHALLEGADA,'IW'),count(*);

SELECT CAST(TO_CHAR("A3"."FECHALLEGADA",'IW') AS int) "SEMANA","A1"."ID" "ID",SUM("A2"."PRECIOESTADIA"*"A3"."CANTIDADDIAS") "INGRESOS",COUNT(*) "NUMRESERVAS" FROM "ISIS2304A021810"."RESERVAS" "A3","ISIS2304A021810"."OFERTAS" "A2","ISIS2304A021810"."OPERADORES" "A1" WHERE "A3"."OFERTA"="A2"."ID" AND "A2"."OPERADOR"="A1"."ID" GROUP BY TO_CHAR("A3"."FECHALLEGADA",'IW'),"A3"."FECHALLEGADA","A1"."ID",CAST(TO_CHAR("A3"."FECHALLEGADA",'IW') AS int) ORDER BY TO_CHAR("A3"."FECHALLEGADA",'IW');

