SELECT CLIENTES.DOCUMENTO, clientes.vinculo, CLIENTES.NOMBRE, ALOJAMIENTOS.TIPO as TipoAlojamiento, RESERVAS.FECHALLEGADA, RESERVAS.CANTIDADDIAS, ofertas.id
FROM CLIENTES, OFERTAS, RESERVAS, RESERVASCLIENTE, alojamientos
WHERE CLIENTES.DOCUMENTO = RESERVASCLIENTE.CLIENTEID
AND RESERVASCLIENTE.RESERVAID= RESERVAS.ID
AND OFERTAS.ID = RESERVAS.OFERTA
AND OFERTAS.ALOJAMIENTOID = ALOJAMIENTOS.ID
and ((ofertas.id <> 1)
OR (RESERVAS.FECHALLEGADA < TO_DATE('1/4/2017','DD/MM/YYYY'))
OR (RESERVAS.FECHALLEGADA > TO_DATE('30/4/2017','DD/MM/YYYY')))
order by NOMBRE;

SELECT "A5"."DOCUMENTO" "DOCUMENTO","A5"."VINCULO" "VINCULO","A5"."NOMBRE" "NOMBRE","A1"."TIPO" "TIPOALOJAMIENTO","A3"."FECHALLEGADA" "FECHALLEGADA","A3"."CANTIDADDIAS" "CANTIDADDIAS","A4"."ID" "ID" FROM "ISIS2304A021810"."CLIENTES" "A5","ISIS2304A021810"."OFERTAS" "A4","ISIS2304A021810"."RESERVAS" "A3","ISIS2304A021810"."RESERVASCLIENTE" "A2","ISIS2304A021810"."ALOJAMIENTOS" "A1" WHERE "A5"."DOCUMENTO"="A2"."CLIENTEID" AND "A2"."RESERVAID"="A3"."ID" AND "A4"."ID"="A3"."OFERTA" AND "A4"."ALOJAMIENTOID"="A1"."ID" AND ("A4"."ID"<>1 OR "A3"."FECHALLEGADA"<TO_DATE('1/4/2017','DD/MM/YYYY') OR "A3"."FECHALLEGADA">TO_DATE('30/4/2017','DD/MM/YYYY')) ORDER BY "A5"."NOMBRE";
