SElECT OPERADORES.NOMBRE,OPERADORES.TIPO, SUM(DiasReservados.PRECIOESTADIA*DIASRESERVADOS.DIAS) As Suma
FROM OPERADORES,(SELECT OFERTAS.OPERADOR, OFERTAS.PRECIOESTADIA,SUM(CASE WHEN RESERVAS.OFERTA=OFERTAS.ID THEN RESERVAS.CANTIDADDIAS ELSE 0 END) As Dias
FROM OFERTAS,RESERVAS 
WHERE EXTRACT(year from RESERVAS.FECHALLEGADA)=2018
GROUP BY OFERTAS.OPERADOR, OFERTAS.PRECIOESTADIA) DiasReservados
WHERE DiasReservados.OPERADOR = OPERADORES.ID
group by OPERADORES.NOMBRE;

SELECT "A2"."NOMBRE" "NOMBRE","A2"."TIPO" "TIPO",SUM("A1"."PRECIOESTADIA"*"A1"."DIAS") "SUMA" FROM "ISIS2304A021810"."OPERADORES" "A2", (SELECT "A4"."OPERADOR" "OPERADOR","A4"."PRECIOESTADIA" "PRECIOESTADIA",SUM(CASE  WHEN "A3"."OFERTA"="A4"."ID" THEN "A3"."CANTIDADDIAS" ELSE 0 END ) "DIAS" FROM "ISIS2304A021810"."OFERTAS" "A4","ISIS2304A021810"."RESERVAS" "A3" WHERE EXTRACT(YEAR FROM "A3"."FECHALLEGADA")=2018 GROUP BY "A4"."OPERADOR","A4"."PRECIOESTADIA") "A1" WHERE "A1"."OPERADOR"="A2"."ID" GROUP BY "A2"."NOMBRE", "A2"."TIPO";

SElECT OPERADORES.NOMBRE,OPERADORES.TIPO, SUM(DiasReservados.PRECIOESTADIA*DIASRESERVADOS.DIAS) As Suma
FROM OPERADORES,(SELECT OFERTAS.OPERADOR, OFERTAS.PRECIOESTADIA,SUM(CASE WHEN RESERVAS.OFERTA=OFERTAS.ID THEN RESERVAS.CANTIDADDIAS ELSE 0 END) As Dias
FROM OFERTAS,RESERVAS 
WHERE EXTRACT(year from RESERVAS.FECHALLEGADA)=2018
GROUP BY OFERTAS.OPERADOR, OFERTAS.PRECIOESTADIA) DiasReservados
WHERE DiasReservados.OPERADOR = OPERADORES.ID
group by OPERADORES.NOMBRE, OPERADORES.TIPO;

SElECT OPERADORES.NOMBRE,OPERADORES.TIPO, SUM(DiasReservados.PRECIOESTADIA*DIASRESERVADOS.DIAS) As Suma
FROM OPERADORES,(SELECT OFERTAS.OPERADOR, OFERTAS.PRECIOESTADIA,SUM(CASE WHEN RESERVAS.OFERTA=OFERTAS.ID THEN RESERVAS.CANTIDADDIAS ELSE 0 END) As Dias
FROM OFERTAS,RESERVAS 
WHERE EXTRACT(year from RESERVAS.FECHALLEGADA)=2018
GROUP BY OFERTAS.OPERADOR, OFERTAS.PRECIOESTADIA) DiasReservados
WHERE DiasReservados.OPERADOR = OPERADORES.ID
group by OPERADORES.NOMBRE, OPERADORES.TIPO;