SELECT T.*
FROM (SELECT OFERTAS.ID, OFERTAS.NOMBRE, SUM(CASE WHEN OFERTAS.ID = RESERVAS.OFERTA THEN 1 ELSE 0 END) AS NumReservas
FROM OFERTAS,RESERVAS 
WHERE RESERVAS.OFERTA=OFERTAS.ID 
GROUP BY OFERTAS.ID , OFERTAS.NOMBRE
ORDER BY COUNT(RESERVAS.OFERTA) DESC) T
WHERE rownum <=20;

SELECT "A1"."ID" "ID","A1"."NOMBRE" "NOMBRE","A1"."NUMRESERVAS" "NUMRESERVAS" FROM  (SELECT "A3"."ID" "ID","A3"."NOMBRE" "NOMBRE",SUM(CASE  WHEN "A3"."ID"="A2"."OFERTA" THEN 1 ELSE 0 END ) "NUMRESERVAS" FROM "ISIS2304A021810"."OFERTAS" "A3","ISIS2304A021810"."RESERVAS" "A2" WHERE "A2"."OFERTA"="A3"."ID" GROUP BY "A3"."ID","A3"."NOMBRE" ORDER BY COUNT("A2"."OFERTA") DESC) "A1" WHERE ROWNUM<=20;
