SELECT OFERTAS.ID, OFERTAS.NOMBRE, OFERTAS.CAPACIDAD, SUM(CASE WHEN OFERTAS.ID = RESERVAS.OFERTA THEN 1 ELSE 0 END) AS NumReservas
FROM OFERTAS,RESERVAS 
GROUP BY OFERTAS.ID, OFERTAS.NOMBRE, OFERTAS.CAPACIDAD
ORDER BY OFERTAS.ID ASC;



