SELECT OFERTAS.ID, OFERTAS.NOMBRE, OFERTAS.CAPACIDAD, SUM(CASE WHEN OFERTAS.ID = RESERVAS.OFERTA THEN 1 ELSE 0 END) AS NumReservas
FROM OFERTAS,RESERVAS 
GROUP BY OFERTAS.ID, OFERTAS.NOMBRE, OFERTAS.CAPACIDAD
ORDER BY OFERTAS.ID ASC;


SELECT "A2"."ID" "ID","A2"."NOMBRE" "NOMBRE","A2"."CAPACIDAD" "CAPACIDAD",SUM(CASE  WHEN "A2"."ID"="A1"."OFERTA" THEN 1 ELSE 0 END ) "NUMRESERVAS" FROM "ISIS2304A021810"."OFERTAS" "A2","ISIS2304A021810"."RESERVAS" "A1" GROUP BY "A2"."ID","A2"."NOMBRE","A2"."CAPACIDAD" ORDER BY "A2"."ID";

