SELECT CLIENTES.VINCULO, STATS_MODE(ALOJAMIENTOS.TIPO) As TipoFrecuente,sum(RESERVAS.CANTIDADDIAS) as dias,sum(OFERTAS.PRECIOESTADIA) as precios
FROM CLIENTES,RESERVASCLIENTE,RESERVAS,OFERTAS,ALOJAMIENTOS
WHERE RESERVASCLIENTE.CLIENTEID=clientes.documento
AND RESERVASCLIENTE.RESERVAID= RESERVAS.ID
AND RESERVAS.OFERTA = OFERTAS.ID
AND OFERTAS.ALOJAMIENTOID=ALOJAMIENTOS.ID 
group by CLIENTES.VINCULO;

SELECT "A5"."VINCULO" "VINCULO",STATS_MODE("A1"."TIPO") "TIPOFRECUENTE",SUM("A3"."CANTIDADDIAS") "DIAS",SUM("A2"."PRECIOESTADIA") "PRECIOS" FROM "ISIS2304A021810"."CLIENTES" "A5","ISIS2304A021810"."RESERVASCLIENTE" "A4","ISIS2304A021810"."RESERVAS" "A3","ISIS2304A021810"."OFERTAS" "A2","ISIS2304A021810"."ALOJAMIENTOS" "A1" WHERE "A4"."CLIENTEID"="A5"."DOCUMENTO" AND "A4"."RESERVAID"="A3"."ID" AND "A3"."OFERTA"="A2"."ID" AND "A2"."ALOJAMIENTOID"="A1"."ID" GROUP BY "A5"."VINCULO";