SELECT CLIENTES.VINCULO, STATS_MODE(ALOJAMIENTOS.TIPO) As TipoFrecuente,sum(RESERVAS.CANTIDADDIAS) as dias,sum(OFERTAS.PRECIOESTADIA) as precios
FROM CLIENTES,RESERVASCLIENTE,RESERVAS,OFERTAS,ALOJAMIENTOS
WHERE RESERVASCLIENTE.CLIENTEID=clientes.documento
AND RESERVASCLIENTE.RESERVAID= RESERVAS.ID
AND RESERVAS.OFERTA = OFERTAS.ID
AND OFERTAS.ALOJAMIENTOID=ALOJAMIENTOS.ID 
group by CLIENTES.VINCULO;