SELECT DISTINCT "A1"."VINCULO" "VINCULO" FROM "ISIS2304A021810"."CLIENTES" "A1";


SELECT CLIENTES.DOCUMENTO,CLIENTES.VINCULO,ALOJAMIENTOS.TIPO,ALOJAMIENTOS.DESCRIPCION,RESERVAS.CANTIDADDIAS,OFERTAS.PRECIOESTADIA
FROM clientes,RESERVASCLIENTE,RESERVAS,OFERTAS,ALOJAMIENTOS
WHERE clientes.vinculo = 'Empleado'
AND RESERVASCLIENTE.CLIENTEID=clientes.documento
AND RESERVASCLIENTE.RESERVAID= RESERVAS.ID
AND RESERVAS.OFERTA = OFERTAS.ID
AND OFERTAS.ALOJAMIENTOID=ALOJAMIENTOS.ID;