SELECT CLIENTES.NOMBRE, STATS_MODE(ALOJAMIENTOS.TIPO) As TipoFrecuente,sum(RESERVAS.CANTIDADDIAS) as dias,sum(OFERTAS.PRECIOESTADIA) as precios
FROM CLIENTES,RESERVASCLIENTE,RESERVAS,OFERTAS,ALOJAMIENTOS
WHERE clientes.documento=4
AND RESERVASCLIENTE.CLIENTEID=clientes.documento
AND RESERVASCLIENTE.RESERVAID= RESERVAS.ID
AND RESERVAS.OFERTA = OFERTAS.ID
AND OFERTAS.ALOJAMIENTOID=ALOJAMIENTOS.ID 
group by CLIENTES.NOMBRE;