SELECT CLIENTES.DOCUMENTO,CLIENTES.VINCULO,ALOJAMIENTOS.TIPO,ALOJAMIENTOS.DESCRIPCION,RESERVAS.CANTIDADDIAS,OFERTAS.PRECIOESTADIA
FROM clientes,RESERVASCLIENTE,RESERVAS,OFERTAS,ALOJAMIENTOS
WHERE clientes.documento=4
AND RESERVASCLIENTE.CLIENTEID=clientes.documento
AND RESERVASCLIENTE.RESERVAID= RESERVAS.ID
AND RESERVAS.OFERTA = OFERTAS.ID
AND OFERTAS.ALOJAMIENTOID=ALOJAMIENTOS.ID;


SELECT "A5"."DOCUMENTO" "DOCUMENTO","A5"."VINCULO" "VINCULO","A1"."TIPO" "TIPO","A1"."DESCRIPCION" "DESCRIPCION","A3"."CANTIDADDIAS" "CANTIDADDIAS","A2"."PRECIOESTADIA" "PRECIOESTADIA" FROM "ISIS2304A021810"."CLIENTES" "A5","ISIS2304A021810"."RESERVASCLIENTE" "A4","ISIS2304A021810"."RESERVAS" "A3","ISIS2304A021810"."OFERTAS" "A2","ISIS2304A021810"."ALOJAMIENTOS" "A1" WHERE "A5"."DOCUMENTO"=4 AND "A4"."CLIENTEID"="A5"."DOCUMENTO" AND "A4"."RESERVAID"="A3"."ID" AND "A3"."OFERTA"="A2"."ID" AND "A2"."ALOJAMIENTOID"="A1"."ID";