SELECT T.*
FROM (SELECT CLIENTES.NOMBRE, CLIENTES.VINCULO, COUNT(*) AS NUMUSOS, SUM(RESERVAS.CANTIDADDIAS) AS NUMDIAS
FROM CLIENTES, RESERVASCLIENTE, RESERVAS, OFERTAS
WHERE CLIENTES.DOCUMENTO = RESERVASCLIENTE.CLIENTEID
AND RESERVASCLIENTE.RESERVAID = RESERVAS.ID
AND RESERVAS.OFERTA = OFERTAS.ID
AND OFERTAS.ALOJAMIENTOID = 1 
group by CLIENTES.NOMBRE, CLIENTES.VINCULO) T
WHERE T.NUMUSOS >= 3 OR T.NUMDIAS >=15;

SELECT CLIENTES.NOMBRE, CLIENTES.VINCULO, COUNT(*) AS NUMUSOS, SUM(RESERVAS.CANTIDADDIAS) AS NUMDIAS
FROM CLIENTES, RESERVASCLIENTE, RESERVAS, OFERTAS
WHERE CLIENTES.DOCUMENTO = RESERVASCLIENTE.CLIENTEID
AND RESERVASCLIENTE.RESERVAID = RESERVAS.ID
AND RESERVAS.OFERTA = OFERTAS.ID
AND OFERTAS.ALOJAMIENTOID = 1 
group by CLIENTES.NOMBRE, CLIENTES.VINCULO;

SELECT "A1"."NOMBRE" "NOMBRE","A1"."VINCULO" "VINCULO","A1"."NUMUSOS" "NUMUSOS","A1"."NUMDIAS" "NUMDIAS" FROM  (SELECT "A5"."NOMBRE" "NOMBRE","A5"."VINCULO" "VINCULO",COUNT(*) "NUMUSOS",SUM("A3"."CANTIDADDIAS") "NUMDIAS" FROM "ISIS2304A021810"."CLIENTES" "A5","ISIS2304A021810"."RESERVASCLIENTE" "A4","ISIS2304A021810"."RESERVAS" "A3","ISIS2304A021810"."OFERTAS" "A2" WHERE "A5"."DOCUMENTO"="A4"."CLIENTEID" AND "A4"."RESERVAID"="A3"."ID" AND "A3"."OFERTA"="A2"."ID" AND "A2"."ALOJAMIENTOID"=1 GROUP BY "A5"."NOMBRE","A5"."VINCULO") "A1" WHERE "A1"."NUMUSOS">=3 OR "A1"."NUMDIAS">=15;