SELECT T.*
FROM (SELECT CLIENTES.NOMBRE, CLIENTES.VINCULO, COUNT(*) AS NUMUSOS, SUM(RESERVAS.CANTIDADDIAS) AS NUMDIAS
FROM CLIENTES, RESERVASCLIENTE, RESERVAS, OFERTAS
WHERE CLIENTES.DOCUMENTO = RESERVASCLIENTE.CLIENTEID
AND RESERVASCLIENTE.RESERVAID = RESERVAS.ID
AND RESERVAS.OFERTA = OFERTAS.ID
AND OFERTAS.ALOJAMIENTOID = 1 
group by CLIENTES.NOMBRE, CLIENTES.VINCULO) T
WHERE T.NUMUSOS >= 3 OR T.NUMDIAS >=15;

SELECT CLIENTES.NOMBRE, CLIENTES.VINCULO, COUNT(*) AS NUMUSOS, SUM(RESERVAS.CANTIDADDIAS) AS NUMDIAS
FROM CLIENTES, RESERVASCLIENTE, RESERVAS, OFERTAS
WHERE CLIENTES.DOCUMENTO = RESERVASCLIENTE.CLIENTEID
AND RESERVASCLIENTE.RESERVAID = RESERVAS.ID
AND RESERVAS.OFERTA = OFERTAS.ID
AND OFERTAS.ALOJAMIENTOID = 1 
group by CLIENTES.NOMBRE, CLIENTES.VINCULO;