SELECT F1.OFERTA AS ID, OFERTAS.NOMBRE,SUM(CASE WHEN OFERTAS.ID=F1.OFERTA THEN 1 ELSE 0 END)+1 AS NUMRESERVAS, MAX(F1.FECHALLEGADA - (F2.FECHALLEGADA+F2.CANTIDADDIAS)) AS DISTANCIA
FROM(SELECT ROWNUM AS ROWN, FECHALLEGADA, CANTIDADDIAS, OFERTA 
FROM(SELECT FECHALLEGADA, CANTIDADDIAS, OFERTA  
FROM RESERVAS 
ORDER BY OFERTA ASC,FECHALLEGADA ASC)) F1,
(SELECT ROWNUM AS ROWN, FECHALLEGADA, CANTIDADDIAS, OFERTA 
FROM(SELECT FECHALLEGADA, CANTIDADDIAS, OFERTA  
FROM RESERVAS 
ORDER BY OFERTA ASC,FECHALLEGADA ASC)) F2,
OFERTAS
WHERE F1.ROWN = F2.ROWN+1 
and F1.OFERTA=F2.OFERTA
and f1.oferta = ofertas.id
GROUP BY F1.OFERTA, OFERTAS.NOMBRE
HAVING MAX(F1.FECHALLEGADA - (F2.FECHALLEGADA+F2.CANTIDADDIAS)) >= 30;

SELECT * FROM
(SELECT OFERTAS.ID, OFERTAS.NOMBRE, SUM(CASE WHEN OFERTAS.ID=RESERVAS.OFERTA THEN 1 ELSE 0 END) AS NUMRESERVAS
FROM OFERTAS,RESERVAS 
group by OFERTAS.ID, OFERTAS.NOMBRE) FRECUENCIAS
WHERE NUMRESERVAS<=1;


SELECT "A3"."OFERTA" "ID","A1"."NOMBRE" "NOMBRE",SUM(CASE  WHEN "A1"."ID"="A3"."OFERTA" THEN 1 ELSE 0 END )+1 "NUMRESERVAS",MAX("A3"."FECHALLEGADA"-("A2"."FECHALLEGADA"+"A2"."CANTIDADDIAS")) "DISTANCIA" FROM  (SELECT ROWNUM "ROWN","A4"."FECHALLEGADA" "FECHALLEGADA","A4"."CANTIDADDIAS" "CANTIDADDIAS","A4"."OFERTA" "OFERTA" FROM  (SELECT "A7"."FECHALLEGADA" "FECHALLEGADA","A7"."CANTIDADDIAS" "CANTIDADDIAS","A7"."OFERTA" "OFERTA" FROM "ISIS2304A021810"."RESERVAS" "A7" ORDER BY "A7"."OFERTA","A7"."FECHALLEGADA") "A4") "A3", (SELECT ROWNUM "ROWN","A5"."FECHALLEGADA" "FECHALLEGADA","A5"."CANTIDADDIAS" "CANTIDADDIAS","A5"."OFERTA" "OFERTA" FROM  (SELECT "A6"."FECHALLEGADA" "FECHALLEGADA","A6"."CANTIDADDIAS" "CANTIDADDIAS","A6"."OFERTA" "OFERTA" FROM "ISIS2304A021810"."RESERVAS" "A6" ORDER BY "A6"."OFERTA","A6"."FECHALLEGADA") "A5") "A2","ISIS2304A021810"."OFERTAS" "A1" WHERE "A3"."ROWN"="A2"."ROWN"+1 AND "A3"."OFERTA"="A2"."OFERTA" AND "A3"."OFERTA"="A1"."ID" GROUP BY "A3"."OFERTA","A1"."NOMBRE" HAVING MAX("A3"."FECHALLEGADA"-("A2"."FECHALLEGADA"+"A2"."CANTIDADDIAS"))>=30;
