SELECT F1.OFERTA, MAX(F1.FECHALLEGADA - (F2.FECHALLEGADA+F2.CANTIDADDIAS)) AS DISTANCIA
FROM(SELECT ROWNUM AS ROWN, FECHALLEGADA, CANTIDADDIAS, OFERTA 
FROM(SELECT FECHALLEGADA, CANTIDADDIAS, OFERTA  
FROM RESERVAS 
ORDER BY OFERTA ASC,FECHALLEGADA ASC)) F1,
(SELECT ROWNUM AS ROWN, FECHALLEGADA, CANTIDADDIAS, OFERTA 
FROM(SELECT FECHALLEGADA, CANTIDADDIAS, OFERTA  
FROM RESERVAS 
ORDER BY OFERTA ASC,FECHALLEGADA ASC)) F2
WHERE F1.ROWN = F2.ROWN+1 and F1.OFERTA=F2.OFERTA
GROUP BY F1.OFERTA
HAVING MAX(F1.FECHALLEGADA - (F2.FECHALLEGADA+F2.CANTIDADDIAS)) >= 30;

SELECT * FROM
(SELECT OFERTAS.ID, SUM(CASE WHEN OFERTAS.ID=RESERVAS.OFERTA THEN 1 ELSE 0 END) AS NUMRESERVAS
FROM OFERTAS,RESERVAS 
group by OFERTAS.ID) FRECUENCIAS
WHERE NUMRESERVAS<=1;

select * from reservas order by oferta;