Insert into AlohAndes(id,nombre) values (1,'AlohAndes');
insert into  Clientes(documento, nombre,vinculo) values(98713,'Mateo','Estudiante');
insert into  Clientes(documento, nombre,vinculo) values(3213124,'Juan','Estudiante');
insert into  Clientes(documento, nombre,vinculo) values(312321312,'Javier','Profesor');
insert into  Clientes(documento, nombre,vinculo) values(821932,'Joshua','Evento');
insert into  Clientes(documento, nombre,vinculo) values(2312321,'Js','Egresado');
insert into  Clientes(documento, nombre,vinculo) values(9819432,'Jaa','Padre');
insert into Operadores(id,tipo,nombre) values (1,'Hotel','Tequendama');
insert into Operadores(id,tipo,nombre) values (2,'Hotel','Inter');
insert into Operadores(id,tipo,nombre) values (3,'Hostal','NocheBuena' );
insert into Operadores(id,tipo,nombre) values (4,'Hostal', 'FirstNuit');
insert into Operadores(id,tipo,nombre) values (5,'Persona', 'Rafael Garzon');
insert into Operadores(id,tipo,nombre) values (6,'Persona', 'Sandra Gibril');
insert into Operadores(id,tipo,nombre) values (7,'Vivienda Universitaria','CityU');
insert into Operadores(id,tipo,nombre) values (8,'Vivienda Universitaria','FeniciaTower');
insert into Servicios(id,nombre,descripcion,costo) values (1,'Bañera','Baño comodo',0);
insert into Servicios(id,nombre,descripcion,costo) values (2,'Yacuzzi', 'Yumi',2313213);
insert into Servicios(id,nombre,descripcion,costo) values (3,'Sala','quiero vagar',0);
insert into Servicios(id,nombre,descripcion,costo) values (4,'Cocineta', 'Plus ',32391);
insert into Servicios(id,nombre,descripcion,costo) values (5,'Wifi', 'Conexion inalambrica',31235);
insert into Servicios(id,nombre,descripcion,costo) values (6,'Recepccion 24', 'dsadsa',0);
insert into Servicios(id,nombre,descripcion,costo) values (7,'Luz', 'dsadas',0);
insert into Servicios(id,nombre,descripcion,costo) values (8,'Agua', 'Cadad',0);
insert into Servicios(id,nombre,descripcion,costo) values (9,'Internet', 'Conexion',31324);
insert into Servicios(id,nombre,descripcion,costo) values (10,'Telefono', 'ewrwr',0);
insert into Servicios(id,nombre,descripcion,costo) values (11,'Restaurante', 'dasdasda',0);
insert into Servicios(id,nombre,descripcion,costo) values (12,'Piscina', 'Cdsadasd',0);
insert into Servicios(id,nombre,descripcion,costo) values (13,'Parqueadero', 'dasada',0);
insert into Servicios(id,nombre,descripcion,costo) values (14,'TV', 'erwrw',232536);
insert into Alojamientos(id,tipo,nombre,ubicacion,descripccion,costo,minimoperiodo)values (1,'general','Nombre','Ubicacion','Descripcion',12.0,30);
insert into Alojamientos(id,tipo,nombre,ubicacion,descripccion,costo,minimoperiodo)values (2,'general','Nombre','Ubicacion','Descripcion',12.0,30);
insert into Alojamientos(id,tipo,nombre,ubicacion,descripccion,costo,minimoperiodo)values (3,'general','Nombre','Ubicacion','Descripcion',12.0,30);
insert into Alojamientos(id,tipo,nombre,ubicacion,descripccion,costo,minimoperiodo)values (4,'general','Nombre','Ubicacion','Descripcion',12.0,30);
insert into Alojamientos(id,tipo,nombre,ubicacion,descripccion,costo,minimoperiodo)values (5,'general','Nombre','Ubicacion','Descripcion',12.0,30);
insert into Alojamientos(id,tipo,nombre,ubicacion,descripccion,costo,minimoperiodo)values (6,'general','Nombre','Ubicacion','Descripcion',12.0,30);
insert into Alojamientos(id,tipo,nombre,ubicacion,descripccion,costo,minimoperiodo)values (7,'general','Nombre','Ubicacion','Descripcion',12.0,30);
insert into Alojamientos(id,tipo,nombre,ubicacion,descripccion,costo,minimoperiodo)values (8,'general','Nombre','Ubicacion','Descripcion',12.0,30);
insert into Alojamientos(id,tipo,nombre,ubicacion,descripccion,costo,minimoperiodo)values (9,'general','Nombre','Ubicacion','Descripcion',12.0,30);
insert into Alojamientos(id,tipo,nombre,ubicacion,descripccion,costo,minimoperiodo)values (10,'general','Nombre','Ubicacion','Descripcion',12.0,30);