insert into ClientesRegistrados(idCliente,idAloha)values(98713,1);
insert into ClientesRegistrados(idCliente,idAloha)values(3213124,1);
insert into ClientesRegistrados(idCliente,idAloha)values(312321312,1);
insert into ClientesRegistrados(idCliente,idAloha)values(821932,1);
insert into ClientesRegistrados(idCliente,idAloha)values(2312321,1);
insert into ClientesRegistrados(idCliente,idAloha)values(9819432,1);
insert into reservascliente(CLIENTEID,reservaid) values (98713,1);
insert into reservascliente(CLIENTEID,reservaid) values (3213124,2);
insert into reservascliente(CLIENTEID,reservaid) values (821932,3);
insert into reservascliente(CLIENTEID,reservaid) values (9819432,4);
insert into SERVICIOSDEALOJAMIENTOS(SERVICIO,ALOJAMIENTO) values (1,2);
insert into SERVICIOSDEALOJAMIENTOS(SERVICIO,ALOJAMIENTO) values (2,2);
insert into SERVICIOSDEALOJAMIENTOS(SERVICIO,ALOJAMIENTO) values (3,2);
insert into SERVICIOSDEALOJAMIENTOS(SERVICIO,ALOJAMIENTO) values (4,2);
insert into SERVICIOSDEALOJAMIENTOS(SERVICIO,ALOJAMIENTO) values (1,3);
insert into SERVICIOSDEALOJAMIENTOS(SERVICIO,ALOJAMIENTO) values (2,3);
insert into SERVICIOSDEALOJAMIENTOS(SERVICIO,ALOJAMIENTO) values (1,1);
insert into SERVICIOSDEALOJAMIENTOS(SERVICIO,ALOJAMIENTO) values (2,1);
insert into SERVICIOSDEALOJAMIENTOS(SERVICIO,ALOJAMIENTO) values (12,2);
insert into SERVICIOSDEALOJAMIENTOS(SERVICIO,ALOJAMIENTO) values (10,2);
insert into ServiciosDeOperadores(servicio, operador) values (1,1);
insert into ServiciosDeOperadores(servicio, operador) values (1,2);
insert into ServiciosDeOperadores(servicio, operador) values (1,3);
insert into ServiciosDeOperadores(servicio, operador) values (2,4);
insert into ServiciosDeOperadores(servicio, operador) values (1,4);
insert into ServiciosDeOperadores(servicio, operador) values (3,7);
insert into ServiciosDeOperadores(servicio, operador) values (10,6);
insert into ServiciosDeOperadores(servicio, operador) values (11,7);
insert into ServiciosDeOperadores(servicio, operador) values (9,8);
insert into ServiciosDeOperadores(servicio, operador) values (4,4);
insert into ServiciosDeOperadores(servicio, operador) values (5,5);
insert into ServiciosDeOperadores(servicio, operador) values (6,8);
