SElECT OPERADORES.ID, OPERADORES.NOMBRE, OPERADORES.TIPO,DiasReservados.PRECIOESTADIA*DIASRESERVADOS.DIAS As Suma
FROM OPERADORES,(SELECT OFERTAS.OPERADOR, OFERTAS.PRECIOESTADIA,SUM(RESERVAS.CANTIDADDIAS) As Dias
FROM OFERTAS,RESERVAS 
WHERE RESERVAS.OFERTA=OFERTAS.ID AND EXTRACT(year from RESERVAS.FECHALLEGADA)=2018
GROUP BY OFERTAS.OPERADOR, OFERTAS.PRECIOESTADIA) DiasReservados
WHERE DiasReservados.OPERADOR = OPERADORES.ID;
