SELECT ALOJAMIENTOS.*
FROM ALOJAMIENTOS,OFERTAS,SERVICIOSDEALOJAMIENTOS,SERVICIOS
WHERE OFERTAS.FECHAPUBLICACION BETWEEN TO_DATE('1/1/2018','DD/MM/YYYY')
AND TO_DATE('1/5/2018','DD/MM/YYYY') 
AND OFERTAS.ALOJAMIENTOID=ALOJAMIENTOS.ID
AND ALOJAMIENTOS.ID=SERVICIOSDEALOJAMIENTOS.ALOJAMIENTO
AND SERVICIOS.ID=SERVICIOSDEALOJAMIENTOS.SERVICIO
AND SERVICIOS.NOMBRE='WiFi';