SELECT RESERVASCLIENTE.CLIENTEID,ALOJAMIENTOS.TIPO,ALOJAMIENTOS.DESCRIPCION,RESERVAS.CANTIDADDIAS,OFERTAS.PRECIOESTADIA
FROM RESERVASCLIENTE,RESERVAS,OFERTAS,ALOJAMIENTOS
WHERE RESERVASCLIENTE.CLIENTEID=4
AND RESERVASCLIENTE.RESERVAID= RESERVAS.ID
AND RESERVAS.OFERTA = OFERTAS.ID
AND OFERTAS.ALOJAMIENTOID=ALOJAMIENTOS.ID;